name: Build mitmproxy for Android ARM64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android-arm64:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Устанавливаем Android NDK
      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c

      # 3. Устанавливаем Python и необходимые инструменты
      - name: Install Python and tools
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip python3-dev
          pip3 install setuptools wheel

      # 4. Устанавливаем Nuitka
      - name: Install Nuitka
        run: |
          pip3 install nuitka

      # 5. Кросс-компиляция mitmproxy для Android ARM64
      - name: Build mitmproxy for Android ARM64
        env:
          ANDROID_NDK_HOME: ${{ github.workspace }}/android-ndk-r25c
        run: |
          # Устанавливаем зависимости mitmproxy из pyproject.toml
          pip3 install .

          # Настраиваем пути для кросс-компиляции под Android ARM64
          export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
          export CC=aarch64-linux-android33-clang
          export CXX=aarch64-linux-android33-clang++
          export LD=aarch64-linux-android-ld

          # Компилируем mitmproxy в бинарник
          python3 -m nuitka \
            --standalone \
            --onefile \
            --assume-yes-for-downloads \
            --output-dir=dist \
            --target-arch=arm64 \
            --clang \
            --lto=yes \
            --static-libpython \
            mitmproxy/main.py

      # 6. Переименовываем бинарник
      - name: Rename binary
        run: |
          mv dist/main.bin mitmproxy-android-arm64

      # 7. Сохраняем бинарник как артефакт
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mitmproxy-android-arm64
          path: mitmproxy-android-arm64

      # 8. (Опционально) Тестируем через ADB
      - name: Test binary via ADB
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          sudo apt-get install -y android-tools-adb
          adb devices
          adb push mitmproxy-android-arm64 /data/local/tmp/mitmproxy
          adb shell chmod +x /data/local/tmp/mitmproxy
          adb shell /data/local/tmp/mitmproxy --version
